### ISSUE TITLE
check_numpy_square_matrix should do validation correctly

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#261]
Currently the function errors out if a 1d numpy array is passed because of a "tuple index out of range" error which is not helpful to the user. Instead we should be doing a check to see if the passed in array is 1d _before_ we compare it's dimensions together.

We should also be attempting to convert it to squareform if it's a 1d numpy array as we already do that if the type in Adjacency and we want to be consistent. @jcheong0428

**Comment by jcheong0428** [comment]
I think @ljchang  wrote that function but I'd be happy to edit. 
Also originally wrote the matrix_perm function as taking the upper triangle (the 1d array case) because that seemed to be what's preferred in Adjacency but now it only takes the full matrix. 
We could discuss whichever is preferred or whether it should attempt to try both conversions.

**Comment by ejolly** [comment]
Ok I add a fix in PR #256

**Comment by ljchang** [comment]
We want to keep things fairly consistent across functions and as a stand alone, that's why i switched it from upper triangle to square.  I've been slowly trying to increase consistency of how functions work and also to make sure everything is funneled correctly.  The new check functions also dramatically reduce the amount of repeated code.

Currently, I think there is a silent error if the matrix size isn't length 2.

Also, I don't understand why we would want to convert a 1d into a squareform with this function.  If this is a desirable behavior, let's make that into its own function for clarity and conciseness.

**Comment by ejolly** [comment]
I'm not sure I understand your concern. I test this locally and the logic is as follows:
1a. If the input is an Adjacency, grab it's squareform output
1b. if the input is a dataframe grab it's values (i.e. numpy array)
1c. otherwise convert input to a numpy array

2. if the data is not a 2d array, try to convert it to one, otherwise raise an error (i.e. if you pass it in a 1d, 3d, Nd, array it will raise an error as it should). If the input is _already_ 2d, then this function should just return the input as it does. 

I changed the behavior, because it was _previously_ consistent: if the input was an Adjacency, it would be converted to a 2d array, however if it was anything else it would just raise an error.

**Comment by ejolly** [comment]
I can see breaking the _conversion_ to 2d into a separate function, but then we should be consistent and _not_ convert it to 2d if it's an Adjacency either. However, doing so will require editing a few other functions that rely on this function _either_ return a 2d array or an error. I vote we leave it because it works as expected.

**Comment by ljchang** [comment]
oh, maybe that's the issue.  Was really hard to do a code review the way I usually do it now.  I couldn't tell which lines were formatting fixes and which were substantive changes.  I'm sure it's fine for now.  This is all a WIP.  I'm just glad that things are slowly getting better.  I did a big code overhaul a few months ago and tried to refactor and remove unused code.  Thanks for helping with this.
