### ISSUE TITLE
TypeError: cannot serialize 'IndexedGzipFile' object

### ISSUE THREAD

**Issue by ljchang** [cosanlab/nltools#281]
In some python environments we have started to observe some serialization errors related to the use of deepcopy.  Unfortunately, most of the Brain_Data methods rely on this function.

We haven't been able to figure out exactly how and why we are observing these errors. However, we can confirm that nltools works in at least Python 3.6.8 distributed via anaconda.

Also, installing fmriprep appears to introduce these errors, but we haven't been to isolate which specific dependency is the culprit.

Please let us know if you have any ideas.

**Comment by tsalo** [comment]
Is this still a problem? I just got the same error in my own code, where I was using `multiprocessing` with `nibabel` images. I finally traced it to [nibabel 2.3](https://nipy.org/nibabel/changelog.html#id14), and reverting to 2.2.1 solved it for me.

**Comment by ejolly** [comment]
@tsalo Thanks for noting this! By chance, have you tried with any nibabel versions >2.3 ? and/or versions of joblib > 0.11? 
Just wondering if the issue is specifically nibabel 2.3 + joblib 0.11 = 😭, and new versions don't have compatibility issues, or whether we should be opening issues on the relevant libraries?

Keep this here for reference https://github.com/nipy/nibabel/pull/614

**Comment by tsalo** [comment]
I am using joblib 0.13.2 and I'm pretty sure I was using nibabel 2.4.1 when I first started getting the error (but don't quote me on it). I tried 2.3.1 and 2.3 and both failed.

**Comment by ljchang** [comment]
Okay, I think I have finally figured out this issue. It has to do with a dependency installed by fmriprep called indexed-gzip, which is supposed to speed up indexing of gzipped nibabel files. Uninstalling the package fixes the issue for me in python 3.7.7
