### ISSUE TITLE
Custom templates for first and second level analyses

### ISSUE THREAD

**Issue by hspopal** [cosanlab/nltools#328]
Hello,

I am trying to use nltools to complete my first and second level analyses of my fMRI data. The voxel sizes of my raw data is 2.512, 2.512, 2.5, with dimensions 78 x 92 x 78 x 206. When I import my data into a Brain_Data object, I can see that the mask is defaulted to MNI152_T1_2mm_brain_mask.nii.gz. I guess the data is automatically resampled when it is uploaded? When I run my analyses, the exported data has the standard MNI152 2mm voxel sizes and the respective dimensions. In the documentation, I found that I can change the default of the Brain_Data template to a 3mm MNI152 brain, but I was wondering if I could use a custom template. For example, the standard brain that was used in my preprocessing with the same voxel size and dimensions as my fMRI data so that I can avoid downsampling. 

Thank you for your help.

**Comment by ejolly** [comment]
Yup that should be possible using `mask` argument in `Brain_Data`. You would do something like this:

`brain = Brain_Data('func_image.nii.gz', mask='custom_mask.nii.gz')`

Now any operations on `brain` should use the same mask. Take care however to make sure that any comparisons between different `Brain_Data` instances also use the same mask otherwise you run the risk of resampling/potentially getting errors without realizing.

**Comment by hspopal** [comment]
When I tried this before, I think I was resampling in some later part of the code, after the initial important. Thank you.

**Comment by hspopal** [comment]
When I tried this before, I think I was resampling in some later part of the code, after the initial important. Thank you.

**Comment by ejolly** [comment]
Gotcha. Feel free to open another issue if you run into one, but I’m gonna close this for now.
