### ISSUE TITLE
design matrix - what are the indexes?

### ISSUE THREAD

**Issue by orko19** [cosanlab/nltools#329]
I look at this tutorial:

> https://neurolearn.readthedocs.io/en/latest/auto_examples/01_DataOperations/plot_design_matrix.html#sphx-glr-auto-examples-01-dataoperations-plot-design-matrix-py

What are the indexes of the dm? I assumed each row is one second, but it can be since TR = 1.5 and there are 22 rows.

So, let's say I have two conditions and experiment of 24 seconds:
Faces with onsets `[5,9,15]`
Houses with onsets `[3,8,20]`
And `TR=2`
How my df should look like before feeding it to the dm?

Thanks in advance!

**Comment by ejolly** [comment]
It's actually up to you whether you choose to use seconds or TRs as the row index, as `Design_Matrix` imposes no restrictions. The `sampling_freq` argument is primarily used when calling the `.convolve()` method to figure out the shape of the hrf or when using `.upsample()` and `.downsample()`

For maximum compatibility with the `Brain_Data` class, and in the tutorial you reference, rows reflect _TRs_ rather than seconds. This way the first axis of both a `Brain_Data` object and `Design_Matrix` object match. I would recommend this if your goal is fMRI analysis.

In your case if you plan to model all faces as 1 condition and all houses as another condition (rather than 2 different faces and 2 different houses modeled independently as in the tutorial) your design matrix will have numTRs rows and 2 columns. 

If a each face lasts exactly 1 TR, then one of your columns will have 0s everywhere except at rows 5,9,15, assuming those numbers are the _TRs_ your stimuli were presented at. If there are the seconds, you need to do the conversion yourself. Same idea for your house condition. If each stimulus lasted more than 1 TR then you need to add additional 1s to the rows it was on.

You can checkout/try the [onsets_to_dm](https://neurolearn.readthedocs.io/en/latest/api.html#nltools.data.Design_Matrix) function which can attempt automatically convert this for you provided a `.csv` file of onsets timings (see the [file reading section](https://neurolearn.readthedocs.io/en/latest/auto_examples/01_DataOperations/plot_design_matrix.html#file-reading) of the design matrix tutorial). However, you may experience some issues as this function hasn't been robustly tested on all possible cases, so definitely manually verify what you're getting out, or simply use it as a guide to write your own similar function. 

Of note, is issue https://github.com/cosanlab/nltools/issues/325 which has not been fixed yet

Hope that helps!
