### ISSUE TITLE
Need to add ipywidgets dependency

### ISSUE THREAD

**Issue by ljchang** [cosanlab/nltools#332]
I guess we can make this an optional module, but necessary for the new interactive component viewer.

**Comment by ejolly** [comment]
@ljchang I had already added it as an optional import in `plotting.py` for the interactive brain viewer [here](https://github.com/cosanlab/nltools/blob/master/nltools/plotting.py#L41), but looks like you duplicated it as a hard import a few lines above...

**Comment by ljchang** [comment]
yeah, right of course the interactive brain viewer needs it. This test was failing on travis, which makes me think that we need to add it to the travis.yml. will look into this. Do we not want it as a required dependency?

**Comment by ejolly** [comment]
Which test are you referring to? The travis.yml on github (hasn't been updated in a while) looks good to me, since it's installing both the requirements.txt and optional-dependencies.txt, so in theory it should work.

Another option to consolidate travis testing and make it easier for end-users to install the optional dependencies is to change the [`extras_require`](https://github.com/cosanlab/nltools/blob/master/setup.py#L21) line in the `setup.py` file. 

We should be able to do something like:

```
# Add to top of file
with open('optional-dependencies.txt') as f:
    opt_requirements = f.read().splitlines()

...
# within setup()
 extras_require = {
    'extras':opt_requirements
    },

```
Then end-users and travis can either install the package like they normally do, or the following ways to get the extra dependencies:

`pip install nltools[extras]`  (pip install)
`pip install git+https://github.com/cosanlab/nltools.git#egg=nltools[extras]` (github install)
`pip install -e .[extras]` (development install)

Haven't tested this exactly, but something like this should work.

**Comment by ljchang** [comment]
It's because I was calling a widget method that you didn't import with optional ones. Just fixed that and will leave it for now.  We can always rethink this in the future, not sure how much these methods will be used.

**Comment by ljchang** [comment]
getting an error with importing interactive component viewer.

**Comment by ejolly** [comment]
for reference, `iplot` was working just fine

**Comment by ljchang** [comment]
yeah, it was because when we moved the imports I fixed to the optional ones, we didn't update the reference to the functions being imported.
