### ISSUE TITLE
Error about nltools package dependency version when installing via terminal

### ISSUE THREAD

**Issue by habbas23** [cosanlab/nltools#361]
I'm trying to install the nltools package via linux terminal and I'm getting the error below. I'm very new to programming, but I think I installed the newest version of nibabel. Any suggestions to successfully install nltools would be great!

Collecting nibabel>=3.0.1 (from nltools==0.4.2)
  Could not find a version that satisfies the requirement nibabel>=3.0.1 (from nltools==0.4.2) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.5.2)
No matching distribution found for nibabel>=3.0.1 (from nltools==0.4.2)

**Comment by paxtonfitzpatrick** [comment]
hi @habbas23, the error you're getting is because the most recent version of `nltools` (0.4.2) depends on `nibabel>=3.0.1`, but the most recent `nibabel` version that's available to you is 2.5.2.  More recent versions do exist, but pip won't consider them because you're running Python 2.7 and all `nibabel` versions after that require `python>=3.6`.

If you want to install `nltools`, you can either:
- upgrade your Python version to at least 3.6 (or install a more recent version in addition to your current one)
- install an older version of `nltools` that supports Python 2.7.  According to their [README](https://github.com/cosanlab/nltools#nltools), the last version that supported Python 2.7 was 0.3.11, so `pip install nltools==0.3.11` should work.

**Comment by habbas23** [comment]
> hi @habbas23, the error you're getting is because the most recent version of `nltools` (0.4.2) depends on `nibabel>=3.0.1`, but the most recent `nibabel` version that's available to you is 2.5.2. More recent versions do exist, but pip won't consider them because you're running Python 2.7 and all `nibabel` versions after that require `python>=3.6`.
> 
> If you want to install `nltools`, you can either:
> 
> * upgrade your Python version to at least 3.6 (or install a more recent version in addition to your current one)
> * install an older version of `nltools` that supports Python 2.7.  According to their [README](https://github.com/cosanlab/nltools#nltools), the last version that supported Python 2.7 was 0.3.11, so `pip install nltools==0.3.11` should work.

Thank you, this worked!
